export default {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                primary: {
                    50: "#f4f6fb",
                    100: "#e8ecf6",
                    200: "#cbd8ec",
                    300: "#9db6dc",
                    400: "#6990c7",
                    500: "#4672b1",
                    600: "#345995",
                    700: "#2b4779",
                    800: "#273e65",
                    900: "#253555",
                    950: "#111827",
                },
            },
        },
        fontFamily: {
            body: [
                "Inter",
                "ui-sans-serif",
                "system-ui",
                "-apple-system",
                "system-ui",
                "Segoe UI",
                "Roboto",
                "Helvetica Neue",
                "Arial",
                "Noto Sans",
                "sans-serif",
                "Apple Color Emoji",
                "Segoe UI Emoji",
                "Segoe UI Symbol",
                "Noto Color Emoji",
            ],
            sans: [
                "Inter",
                "ui-sans-serif",
                "system-ui",
                "-apple-system",
                "system-ui",
                "Segoe UI",
                "Roboto",
                "Helvetica Neue",
                "Arial",
                "Noto Sans",
                "sans-serif",
                "Apple Color Emoji",
                "Segoe UI Emoji",
                "Segoe UI Symbol",
                "Noto Color Emoji",
            ],
        },
    },
};
